package com.login.Pojos;
// Generated Apr 22, 2018 12:58:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="mydb"
)
public class Admin  implements java.io.Serializable {


     private int stockmanagerIdstockmanager;
     private Stockmanager stockmanager;
     private String adminname;

    public Admin() {
    }

    public Admin(Stockmanager stockmanager, String adminname) {
       this.stockmanager = stockmanager;
       this.adminname = adminname;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="stockmanager"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="stockmanager_idstockmanager", unique=true, nullable=false)
    public int getStockmanagerIdstockmanager() {
        return this.stockmanagerIdstockmanager;
    }
    
    public void setStockmanagerIdstockmanager(int stockmanagerIdstockmanager) {
        this.stockmanagerIdstockmanager = stockmanagerIdstockmanager;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Stockmanager getStockmanager() {
        return this.stockmanager;
    }
    
    public void setStockmanager(Stockmanager stockmanager) {
        this.stockmanager = stockmanager;
    }

    
    @Column(name="adminname", nullable=false, length=45)
    public String getAdminname() {
        return this.adminname;
    }
    
    public void setAdminname(String adminname) {
        this.adminname = adminname;
    }




}


