package com.login.Pojos;
// Generated Apr 22, 2018 12:58:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomerService generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="mydb"
)
public class CustomerService  implements java.io.Serializable {


     private int idcustomer;
     private String customername;
     private String customeremail;
     private String customerpasswd;
     private String customeraddress;
     private String customerphone;

    public CustomerService() {
    }

    public CustomerService(int idcustomer, String customername, String customeremail, String customerpasswd, String customeraddress, String customerphone) {
       this.idcustomer = idcustomer;
       this.customername = customername;
       this.customeremail = customeremail;
       this.customerpasswd = customerpasswd;
       this.customeraddress = customeraddress;
       this.customerphone = customerphone;
    }
   
     @Id 

    
    @Column(name="idcustomer", unique=true, nullable=false)
    public int getIdcustomer() {
        return this.idcustomer;
    }
    
    public void setIdcustomer(int idcustomer) {
        this.idcustomer = idcustomer;
    }

    
    @Column(name="customername", nullable=false, length=45)
    public String getCustomername() {
        return this.customername;
    }
    
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    
    @Column(name="customeremail", nullable=false, length=45)
    public String getCustomeremail() {
        return this.customeremail;
    }
    
    public void setCustomeremail(String customeremail) {
        this.customeremail = customeremail;
    }

    
    @Column(name="customerpasswd", nullable=false, length=45)
    public String getCustomerpasswd() {
        return this.customerpasswd;
    }
    
    public void setCustomerpasswd(String customerpasswd) {
        this.customerpasswd = customerpasswd;
    }

    
    @Column(name="customeraddress", nullable=false, length=90)
    public String getCustomeraddress() {
        return this.customeraddress;
    }
    
    public void setCustomeraddress(String customeraddress) {
        this.customeraddress = customeraddress;
    }

    
    @Column(name="customerphone", nullable=false, length=45)
    public String getCustomerphone() {
        return this.customerphone;
    }
    
    public void setCustomerphone(String customerphone) {
        this.customerphone = customerphone;
    }




}


