package com.login.Pojos;
// Generated Apr 22, 2018 12:58:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Stockmanager generated by hbm2java
 */
@Entity
@Table(name="stockmanager"
    ,catalog="mydb"
)
public class Stockmanager  implements java.io.Serializable {


     private int idstockmanager;
     private String stockmanagername;
     private String stockmanageremail;
     private String stockmanagerpasswd;
     private String stockmanagerphone;
     private Admin admin;

    public Stockmanager() {
    }

	
    public Stockmanager(int idstockmanager, String stockmanagername, String stockmanageremail, String stockmanagerpasswd, String stockmanagerphone) {
        this.idstockmanager = idstockmanager;
        this.stockmanagername = stockmanagername;
        this.stockmanageremail = stockmanageremail;
        this.stockmanagerpasswd = stockmanagerpasswd;
        this.stockmanagerphone = stockmanagerphone;
    }
    public Stockmanager(int idstockmanager, String stockmanagername, String stockmanageremail, String stockmanagerpasswd, String stockmanagerphone, Admin admin) {
       this.idstockmanager = idstockmanager;
       this.stockmanagername = stockmanagername;
       this.stockmanageremail = stockmanageremail;
       this.stockmanagerpasswd = stockmanagerpasswd;
       this.stockmanagerphone = stockmanagerphone;
       this.admin = admin;
    }
   
     @Id 

    
    @Column(name="idstockmanager", unique=true, nullable=false)
    public int getIdstockmanager() {
        return this.idstockmanager;
    }
    
    public void setIdstockmanager(int idstockmanager) {
        this.idstockmanager = idstockmanager;
    }

    
    @Column(name="stockmanagername", nullable=false, length=45)
    public String getStockmanagername() {
        return this.stockmanagername;
    }
    
    public void setStockmanagername(String stockmanagername) {
        this.stockmanagername = stockmanagername;
    }

    
    @Column(name="stockmanageremail", nullable=false, length=45)
    public String getStockmanageremail() {
        return this.stockmanageremail;
    }
    
    public void setStockmanageremail(String stockmanageremail) {
        this.stockmanageremail = stockmanageremail;
    }

    
    @Column(name="stockmanagerpasswd", nullable=false, length=45)
    public String getStockmanagerpasswd() {
        return this.stockmanagerpasswd;
    }
    
    public void setStockmanagerpasswd(String stockmanagerpasswd) {
        this.stockmanagerpasswd = stockmanagerpasswd;
    }

    
    @Column(name="stockmanagerphone", nullable=false, length=45)
    public String getStockmanagerphone() {
        return this.stockmanagerphone;
    }
    
    public void setStockmanagerphone(String stockmanagerphone) {
        this.stockmanagerphone = stockmanagerphone;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="stockmanager")
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }




}


